name: Deploy Automático na Oracle Cloud

on:
  push:
    branches:
      - main # O script só roda quando você mandar código para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Acessar servidor e atualizar a API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/TCC-USP
            git pull origin main
            sudo docker build -t api-tcc-git .
            sudo docker rm -f tcc-backend || true
            sudo docker run -d -p 80:8080 --name tcc-backend api-tcc-git